image: python:3.6
stages:
  - build
  - test

install_dependencies:
  stage: build
  script:
    - pip install -r requirements.txt
    
unittest:
  stage: test
  script:
    - python -m unittest discover -v